import { generateGpx } from './generation/generate-gpx.js';
import { generateKml } from './generation/generate-kml.js';
import { createGenerationReceipt } from './generation/generation-receipt.js';
import { compareResolvedLocations } from './generation/route-comparison.js';
import { downloadGeneratedText, downloadReceipt } from './export/export-generated-route.js';
import { parseMapLink } from './acquisition/parse-map-link.js';
import { resolveGoogleMapsShortLink, SHORT_LINK_GATEWAY_STORAGE_KEY, validateGatewayEndpoint } from './acquisition/short-link-resolver.js';
import { acquisitionBudgetStatus } from './acquisition/acquisition-budget.js';
import { createProviderAdapter, PROVIDERS } from './providers/provider-registry.js';
import { clearProviderSettings, loadProviderSettings, saveProviderSettings } from './storage/provider-settings.js';
import { readValidatedImage } from './media/image-security.js';
import { fetchMapMosaic, MAP_PROVIDER } from './map/map-background.js';
import { parseRouteFile } from './import/parse-route-file.js';
import { parseGpx } from './gpx/parse-gpx.js';
import { calculateStatistics, elevationMetricDescription, formatDistance, formatElevation } from './domain/route-statistics.js';
import { createPosterSvg } from './render/poster-svg.js?v=elevation-range-20260728';
import { LAYOUT_PRESETS } from './render/layout-presets.js';
import { downloadSvg } from './export/export-svg.js';
import { downloadPng } from './export/export-png.js';
import { downloadJpeg } from './export/export-jpeg.js';
import { createProject, updateProject, validateProject } from './project/project-model.js';
import { exportProjectFile, importProjectFile } from './project/project-file.js';
import { listProjects, loadProject, saveProject } from './storage/indexeddb.js';

const $ = (selector) => document.querySelector(selector);
const elements = {
  file: $('#route-file'), projectFile: $('#project-file'), dropZone: $('#drop-zone'), status: $('#file-status'), controls: $('#story-controls'),
  title: $('#story-title'), subtitle: $('#story-subtitle'), backgroundMode: $('#background-mode'), backgroundImage: $('#background-image'), backgroundOpacity: $('#background-opacity'), overlayOpacity: $('#overlay-opacity'), mapConsent: $('#map-consent'), mapStatus: $('#map-status'), mapHelp: $('#map-help'), mapZoomOut: $('#map-zoom-out'), mapZoomIn: $('#map-zoom-in'), mapZoomStatus: $('#map-zoom-status'), lineWidth: $('#line-width'), showElevation: $('#show-elevation'), showDuration: $('#show-duration'), showMarkers: $('#show-markers'), layout: $('#layout'), units: $('#units'), routeColour: $('#route-colour'), backgroundColour: $('#background-colour'), textColour: $('#text-colour'),
  downloadSvg: $('#download-svg'), downloadPng: $('#download-png'), downloadJpeg: $('#download-jpeg'), pngScale: $('#png-scale'), reset: $('#reset'), sample: $('#load-sample'), preview: $('#poster-preview'), provenance: $('#route-provenance'), summary: $('#route-summary'), summaryType: $('#summary-type'), summaryFormat: $('#summary-format'), summaryPoints: $('#summary-points'), summarySegments: $('#summary-segments'), summaryDistance: $('#summary-distance'), summaryAscentLabel: $('#summary-ascent-label'), summaryAscent: $('#summary-ascent'), summaryRange: $('#summary-range'), summaryHighest: $('#summary-highest'), summaryLowest: $('#summary-lowest'), summaryAscentHelp: $('#summary-ascent-help'), warnings: $('#import-warnings'),
  mapLink: $('#map-link'), reviewMapLink: $('#review-map-link'), expandMapLink: $('#expand-map-link'), resolverEndpoint: $('#resolver-endpoint'), rememberResolver: $('#remember-resolver'), mapLinkStatus: $('#map-link-status'), intentReview: $('#route-intent-review'), intentSource: $('#intent-source'), intentOrigin: $('#intent-origin'), intentDestination: $('#intent-destination'), intentWaypoints: $('#intent-waypoints'), intentMode: $('#intent-mode'), intentWarnings: $('#intent-warnings'),
  providerPanel: $('#provider-panel'), generatedReview: $('#generated-route-review'), generatedProvider: $('#generated-provider'), generatedMode: $('#generated-mode'), generatedPoints: $('#generated-points'), generatedAt: $('#generated-at'), generatedHash: $('#generated-hash'), generatedWarnings: $('#generated-warnings'), denseGpx: $('#dense-gpx'), downloadGeneratedGpx: $('#download-generated-gpx'), downloadGeneratedKml: $('#download-generated-kml'), downloadReceipt: $('#download-receipt'), provider: $('#routing-provider'), providerKey: $('#provider-api-key'), rememberProvider: $('#remember-provider'), clearProvider: $('#clear-provider'), resolvePlaces: $('#resolve-places'), candidatePanel: $('#candidate-panel'), candidateList: $('#candidate-list'), buildRoute: $('#build-route'), providerStatus: $('#provider-status'), providerBudget: $('#provider-budget'),
  annotationLabel: $('#annotation-label'), annotationPosition: $('#annotation-position'), addAnnotation: $('#add-annotation'), clearAnnotations: $('#clear-annotations'), annotationStatus: $('#annotation-status'), saveProject: $('#save-project'), openLatest: $('#open-latest-project'), exportProject: $('#export-project'), importProject: $('#import-project')
};
let route=null,statistics=null,currentSvg='',currentProject=null,renderFrame=0,operation=0,backgroundAsset=null,mapConsentGranted=false,mapLoading=false,annotations=[],currentIntent=null,resolvedLocations=[],mapZoomAdjustment=0,currentReceipt=null,currentGeneratedGpx='',currentGeneratedKml='',currentShortResolution=null,shortResolutionController=null;

function locationLabel(location){if(!location)return'Not recovered';if(location.coordinates)return`${location.coordinates.latitude.toFixed(5)}, ${location.coordinates.longitude.toFixed(5)}`;return location.label||location.rawValue||'Unresolved';}
function renderList(element,items){element.replaceChildren(...items.map((text)=>{const item=document.createElement('li');item.textContent=text;return item;}));element.hidden=items.length===0;}
function providerAdapter(){const settings={providerId:elements.provider.value,apiKey:elements.providerKey.value.trim(),remember:elements.rememberProvider.checked};saveProviderSettings(settings);return createProviderAdapter(settings.providerId,{apiKey:settings.apiKey});}
function updateBudget(){const budget=acquisitionBudgetStatus();elements.providerBudget.textContent=`External request budget: ${budget.remaining} of ${budget.maximum} remaining this session.`;}
function orderedIntentLocations(){return [currentIntent.origin,...currentIntent.waypoints,currentIntent.destination].filter(Boolean);}
function showProviderPanel(){elements.providerPanel.hidden=false;elements.providerPanel.scrollIntoView({behavior:'smooth',block:'nearest'});elements.resolvePlaces.focus({preventScroll:true});}
function displayIntent(intent){currentIntent=intent;elements.intentReview.hidden=false;elements.intentSource.textContent=intent.source.type==='google-short-link'?'Google Maps short link':'Google Maps directions URL';elements.intentOrigin.textContent=locationLabel(intent.origin);elements.intentDestination.textContent=locationLabel(intent.destination);elements.intentWaypoints.textContent=intent.waypoints.length?intent.waypoints.map(locationLabel).join(' → '):'None recovered';elements.intentMode.textContent=intent.travelMode||'Not encoded';renderList(elements.intentWarnings,intent.warnings);if(intent.source.type!=='google-short-link'&&intent.origin&&intent.destination)showProviderPanel();else elements.providerPanel.hidden=true;}
function reviewMapLink(){try{currentShortResolution=null;const intent=parseMapLink(elements.mapLink.value);displayIntent(intent);const short=intent.source.type==='google-short-link';elements.expandMapLink.hidden=!short;elements.mapLinkStatus.textContent=short?'Short link detected. Configure the resolver endpoint, then press “Expand short link and review”.':'Step 1 complete. Review the recovered intent, then resolve named places in Step 2.';}catch(error){currentIntent=null;elements.intentReview.hidden=true;elements.providerPanel.hidden=true;elements.expandMapLink.hidden=true;elements.mapLinkStatus.textContent=error instanceof Error?error.message:'The map link could not be reviewed.';}}
function saveResolverEndpoint(){const value=elements.resolverEndpoint.value.trim();if(elements.rememberResolver.checked&&value)localStorage.setItem(SHORT_LINK_GATEWAY_STORAGE_KEY,value);else localStorage.removeItem(SHORT_LINK_GATEWAY_STORAGE_KEY);}
async function expandShortLink(){if(shortResolutionController)shortResolutionController.abort();shortResolutionController=new AbortController();try{elements.expandMapLink.disabled=true;elements.reviewMapLink.disabled=true;elements.mapLinkStatus.textContent='Expanding the approved Google Maps short link…';const endpoint=validateGatewayEndpoint(elements.resolverEndpoint.value);saveResolverEndpoint();const resolution=await resolveGoogleMapsShortLink(elements.mapLink.value,{endpoint,signal:shortResolutionController.signal});currentShortResolution=resolution;elements.mapLink.value=resolution.finalUrl;const intent=parseMapLink(resolution.finalUrl);intent.source.originalShortUrl=resolution.sourceUrl;intent.source.resolution={finalHost:resolution.finalHost,redirectCount:resolution.redirectCount,resolvedAt:resolution.resolvedAt};intent.warnings=[...(intent.warnings||[]),`Short link expanded through ${resolution.redirectCount} approved redirect${resolution.redirectCount===1?'':'s'}.`];displayIntent(intent);elements.expandMapLink.hidden=true;elements.mapLinkStatus.textContent='Short link expanded. Review the recovered route intent, then continue to Step 2.';}catch(error){elements.mapLinkStatus.textContent=error?.name==='AbortError'?'Short-link expansion cancelled.':error instanceof Error?error.message:'The short link could not be expanded.';}finally{elements.expandMapLink.disabled=false;elements.reviewMapLink.disabled=false;shortResolutionController=null;}}
function makeRouteFromProvider(result,intent){const segment={id:'provider-route-1',points:result.points};return{schemaVersion:'1.0',id:`generated-${crypto.randomUUID()}`,title:`${locationLabel(intent.origin)} to ${locationLabel(intent.destination)}`.slice(0,120),sourceType:'planned-route',segments:[segment],points:segment.points,source:{type:'generated-route',name:'Resolved map-link route',provider:result.provider.id,attribution:result.rawAttribution},provenance:{geometrySource:'planned-route',provider:result.provider.id,generatedAt:new Date().toISOString(),routeIntentId:intent.id,externalProcessing:true,warnings:['This route was reconstructed by an external routing provider. It is not evidence of completed travel.']}};}
function renderCandidateSelectors(entries){elements.candidateList.replaceChildren(...entries.map((entry,index)=>{const wrapper=document.createElement('div');wrapper.className='candidate-row';const label=document.createElement('label');label.textContent=`${index===0?'Origin':index===entries.length-1?'Destination':`Waypoint ${index}`}: ${entry.location.label||entry.location.rawValue}`;if(entry.location.coordinates){const value=document.createElement('span');value.className='resolved-coordinate';value.textContent=locationLabel(entry.location);label.append(value);wrapper.append(label);}else{const select=document.createElement('select');select.dataset.locationIndex=String(index);for(const [candidateIndex,candidate] of entry.candidates.entries()){const option=document.createElement('option');option.value=String(candidateIndex);option.textContent=[candidate.label,candidate.locality,candidate.country].filter(Boolean).join(' · ');select.append(option);}label.append(select);wrapper.append(label);}return wrapper;}));elements.candidatePanel.hidden=false;elements.buildRoute.disabled=false;}
async function resolvePlaces(){if(!currentIntent)return;try{elements.resolvePlaces.disabled=true;elements.buildRoute.disabled=true;elements.providerStatus.textContent='Resolving named places with the selected provider…';const adapter=providerAdapter();const entries=[];for(const location of orderedIntentLocations()){entries.push({location,candidates:location.coordinates?[]:await adapter.geocode(location.rawValue)});}resolvedLocations=entries;renderCandidateSelectors(entries);elements.providerStatus.textContent='Review each resolved place. Change any ambiguous selection before building the planned route.';updateBudget();}catch(error){elements.providerStatus.textContent=error instanceof Error?error.message:'Place resolution failed.';}finally{elements.resolvePlaces.disabled=false;}}
function selectedLocations(){return resolvedLocations.map((entry,index)=>{if(entry.location.coordinates)return{label:entry.location.label,coordinates:{...entry.location.coordinates}};const select=elements.candidateList.querySelector(`select[data-location-index="${index}"]`);const candidate=entry.candidates[Number(select?.value||0)];if(!candidate)throw new Error('Choose a provider candidate for every named place.');return candidate;});}
async function buildResolvedRoute(){try{elements.buildRoute.disabled=true;elements.providerStatus.textContent='Building the confirmed planned route…';const adapter=providerAdapter();const confirmed=selectedLocations();const result=await adapter.route(confirmed,{travelMode:currentIntent.travelMode||'driving'});const generated=makeRouteFromProvider(result,currentIntent);const displacementWarnings=compareResolvedLocations(orderedIntentLocations(),confirmed);currentReceipt=await createGenerationReceipt({intent:currentIntent,route:generated,provider:result.provider,confirmedLocations:confirmed,travelMode:currentIntent.travelMode||'driving',warnings:displacementWarnings,sourceResolution:currentShortResolution});currentGeneratedGpx=generateGpx(generated,currentReceipt);currentGeneratedKml=generateKml(generated,currentReceipt);applyRoute(generated,'Provider-generated planned route');elements.providerStatus.textContent='Planned route created. Review provenance and export route data in Step 3, then compose the route story in Step 4.';elements.provenance.textContent=`${result.provider.name} reconstructed planned route`;elements.generatedProvider.textContent=result.provider.name;elements.generatedMode.textContent=currentIntent.travelMode||'driving';elements.generatedPoints.textContent=generated.points.length.toLocaleString();elements.generatedAt.textContent=new Date(currentReceipt.generatedAt).toLocaleString();elements.generatedHash.textContent=`${currentReceipt.sourceIntentHash.slice(0,16)}…`;renderList(elements.generatedWarnings,currentReceipt.warnings);elements.generatedReview.hidden=false;elements.generatedReview.scrollIntoView({behavior:'smooth',block:'start'});elements.downloadGeneratedGpx.focus({preventScroll:true});updateBudget();}catch(error){elements.providerStatus.textContent=error instanceof Error?error.message:'Route generation failed.';}finally{elements.buildRoute.disabled=false;}}

function compositionState(){return{annotations:[...annotations],background:backgroundAsset?{...backgroundAsset,mode:elements.backgroundMode.value,opacity:Number(elements.backgroundOpacity.value),overlayOpacity:Number(elements.overlayOpacity.value)}:{mode:elements.backgroundMode.value,opacity:Number(elements.backgroundOpacity.value),overlayOpacity:Number(elements.overlayOpacity.value)},title:elements.title.value,subtitle:elements.subtitle.value,lineWidth:elements.lineWidth.value,showElevation:elements.showElevation.checked,showDuration:elements.showDuration.checked,showMarkers:elements.showMarkers.checked,layout:elements.layout.value,units:elements.units.value,routeColour:elements.routeColour.value,backgroundColour:elements.backgroundColour.value,textColour:elements.textColour.value};}
function applyComposition(composition={}){const values={background:{mode:'solid',opacity:1,overlayOpacity:.18},title:route?.title||'My route story',subtitle:'',lineWidth:'7',showElevation:true,showDuration:true,showMarkers:true,layout:'portrait',units:'metric',routeColour:'#f7f3e9',backgroundColour:'#0b0f0c',textColour:'#f5f1e8',...composition};annotations=Array.isArray(values.annotations)?values.annotations.slice(0,500):[];elements.annotationStatus.textContent=annotations.length?`${annotations.length} annotation${annotations.length===1?'':'s'} added.`:'No annotations added.';backgroundAsset=values.background?.dataUrl?{...values.background}:null;mapZoomAdjustment=Number(values.background?.zoomAdjustment||0);elements.backgroundMode.value=values.background?.mode||'solid';elements.backgroundOpacity.value=values.background?.opacity??1;elements.overlayOpacity.value=values.background?.overlayOpacity??.18;updateBackgroundControls();updateMapZoomStatus();elements.title.value=values.title;elements.subtitle.value=values.subtitle;elements.lineWidth.value=values.lineWidth;elements.showElevation.checked=values.showElevation;elements.showDuration.checked=values.showDuration;elements.showMarkers.checked=values.showMarkers;elements.layout.value=values.layout;elements.units.value=values.units;elements.routeColour.value=values.routeColour;elements.backgroundColour.value=values.backgroundColour;elements.textColour.value=values.textColour;}
function renderWarnings(warnings){renderList(elements.warnings,warnings);}
function renderSummary(){const units=elements.units.value;elements.summary.hidden=false;elements.summaryType.textContent=route.sourceType==='planned-route'?'Planned route':'Recorded track';elements.summaryFormat.textContent=String(route.source?.type||'route').toUpperCase();elements.summaryPoints.textContent=route.points.length.toLocaleString();elements.summarySegments.textContent=route.segments.length.toLocaleString();elements.summaryDistance.textContent=formatDistance(statistics.distanceMetres,units);elements.summaryAscentLabel.textContent='Total climb';elements.summaryAscent.textContent=Number.isFinite(statistics.elevationGainMetres)?formatElevation(statistics.elevationGainMetres,units):'Not available';elements.summaryRange.textContent=Number.isFinite(statistics.elevationRangeMetres)?formatElevation(statistics.elevationRangeMetres,units):'Not available';elements.summaryHighest.textContent=Number.isFinite(statistics.maximumElevationMetres)?formatElevation(statistics.maximumElevationMetres,units):'Not available';elements.summaryLowest.textContent=Number.isFinite(statistics.minimumElevationMetres)?formatElevation(statistics.minimumElevationMetres,units):'Not available';elements.summaryAscentHelp.textContent=elevationMetricDescription(route);renderWarnings(route.provenance.warnings);}
function renderNow(){renderFrame=0;if(!route)return;currentSvg=createPosterSvg({route,statistics,title:elements.title.value.trim()||route.title,subtitle:elements.subtitle.value.trim(),lineWidth:elements.lineWidth.value,showElevation:elements.showElevation.checked,showDuration:elements.showDuration.checked,showMarkers:elements.showMarkers.checked,layout:elements.layout.value,units:elements.units.value,routeColor:elements.routeColour.value,backgroundColor:elements.backgroundColour.value,background:backgroundAsset?{...backgroundAsset,mode:elements.backgroundMode.value,opacity:Number(elements.backgroundOpacity.value),overlayOpacity:Number(elements.overlayOpacity.value)}:{mode:elements.backgroundMode.value},textColor:elements.textColour.value,annotations});elements.preview.replaceChildren();elements.preview.insertAdjacentHTML('afterbegin',currentSvg);elements.preview.style.aspectRatio=LAYOUT_PRESETS[elements.layout.value].ratio;renderSummary();}
function updateExportAvailability(){const blocked=elements.backgroundMode.value==='map'&&(!backgroundAsset||backgroundAsset.mode!=='map'||mapLoading);elements.downloadSvg.disabled=blocked;elements.downloadPng.disabled=blocked;elements.downloadJpeg.disabled=blocked;}
function updateMapZoomStatus(){const labels={'-2':'Wide context','-1':'Wider','0':'Fit whole route','1':'Closer (may crop)','2':'Closest (may crop)'};elements.mapZoomStatus.textContent=labels[String(mapZoomAdjustment)]||'Fit whole route';elements.mapZoomOut.disabled=mapLoading||mapZoomAdjustment<=-2;elements.mapZoomIn.disabled=mapLoading||mapZoomAdjustment>=2;}
function updateBackgroundControls(){const mode=elements.backgroundMode.value;$('#photo-controls').hidden=mode!=='photo';const panel=$('#map-controls');panel.hidden=mode!=='map';if(mode==='map'&&(!backgroundAsset||backgroundAsset.mode!=='map')){panel.classList.add('attention');panel.scrollIntoView({behavior:'smooth',block:'center'});elements.mapConsent.focus({preventScroll:true});elements.mapStatus.textContent='Map selected, but not loaded. Press “Consent and load map now” before export.';elements.mapHelp.hidden=true;}updateMapZoomStatus();updateExportAvailability();}
async function handlePhoto(file){try{elements.status.textContent='Validating photograph locally…';backgroundAsset=await readValidatedImage(file);elements.backgroundMode.value='photo';updateBackgroundControls();elements.status.textContent='Photograph added locally.';scheduleRender();}catch(error){elements.status.textContent=error instanceof Error?error.message:'The photograph could not be loaded.';}}
async function loadMap(){if(!route)return;try{mapLoading=true;updateMapZoomStatus();updateExportAvailability();mapConsentGranted=true;elements.mapConsent.disabled=true;elements.mapHelp.hidden=true;elements.mapStatus.textContent=`Loading up to 9 tiles from ${MAP_PROVIDER.name}…`;backgroundAsset=await fetchMapMosaic(route,{zoomAdjustment:mapZoomAdjustment});elements.backgroundMode.value='map';elements.mapStatus.textContent=`${MAP_PROVIDER.attribution}. ${backgroundAsset.cropped?'Closer view loaded; route ends may be cropped.':'Map fitted to the route.'}`;elements.status.textContent='Map background loaded and aligned to the route.';$('#map-controls').classList.remove('attention');scheduleRender();}catch(error){backgroundAsset=null;elements.mapStatus.textContent=error instanceof Error?error.message:'Map tiles could not be loaded.';elements.status.textContent='Map background unavailable. No blocked tile was added to the poster.';elements.mapHelp.hidden=false;mapConsentGranted=false;}finally{mapLoading=false;elements.mapConsent.disabled=false;updateMapZoomStatus();updateExportAvailability();}}
async function adjustMapZoom(delta){mapZoomAdjustment=Math.max(-2,Math.min(2,mapZoomAdjustment+delta));updateMapZoomStatus();if(mapConsentGranted||backgroundAsset?.mode==='map')await loadMap();else elements.mapStatus.textContent='Choose the desired zoom, then press “Consent and load map now”.';}
function scheduleRender(){if(!renderFrame)renderFrame=window.requestAnimationFrame(renderNow);}
function sourceLabel(nextRoute){return`${String(nextRoute.source?.type||'route').toUpperCase()} ${nextRoute.sourceType==='planned-route'?'planned route':'recorded track'}`;}
function applyRoute(nextRoute,label,composition=null,project=null){route=nextRoute;statistics=calculateStatistics(route.segments);currentProject=project;elements.controls.disabled=false;applyComposition(composition||{title:route.title||'My route story'});elements.status.textContent=`${label}: ${route.points.length.toLocaleString()} points loaded.`;elements.provenance.textContent=sourceLabel(route);scheduleRender();}
async function loadFile(file){const token=++operation;try{elements.status.textContent=`Reading ${file.name}…`;const parsed=await parseRouteFile(file);if(token===operation)applyRoute(parsed,file.name);}catch(error){if(token===operation)fail(error);}}
function fail(error){route=null;statistics=null;currentSvg='';currentProject=null;elements.controls.disabled=true;elements.summary.hidden=true;elements.preview.innerHTML='<div class="empty-state"><p>Route could not be loaded.</p><span>Review the message and try another route source.</span></div>';elements.status.textContent=error instanceof Error?error.message:'The route could not be loaded.';elements.provenance.textContent='Import failed';}
function reset(){operation+=1;if(shortResolutionController)shortResolutionController.abort();currentShortResolution=null;currentReceipt=null;currentGeneratedGpx='';currentGeneratedKml='';elements.generatedReview.hidden=true;backgroundAsset=null;annotations=[];mapZoomAdjustment=0;elements.annotationStatus.textContent='No annotations added.';mapConsentGranted=false;route=null;statistics=null;currentSvg='';currentProject=null;elements.file.value='';elements.projectFile.value='';elements.controls.disabled=true;elements.summary.hidden=true;elements.status.textContent='No route loaded.';elements.provenance.textContent='Awaiting source';elements.preview.style.aspectRatio='4 / 5';elements.preview.innerHTML='<div class="empty-state"><p>Your route poster will appear here.</p><span>Resolve a map link, import GPX or KML, open a project, or use the sample route.</span></div>';}
async function handleJpegExport(){if(!currentSvg)return;elements.downloadJpeg.disabled=true;elements.status.textContent='Rendering JPEG locally…';try{await downloadJpeg(currentSvg,LAYOUT_PRESETS[elements.layout.value],Number(elements.pngScale.value),elements.title.value,elements.layout.value);elements.status.textContent='JPEG download prepared locally.';}catch(error){elements.status.textContent=error instanceof Error?error.message:'JPEG export failed.';}finally{updateExportAvailability();}}
async function handlePngExport(){if(!currentSvg)return;elements.downloadPng.disabled=true;elements.status.textContent='Rendering PNG locally…';try{await downloadPng(currentSvg,LAYOUT_PRESETS[elements.layout.value],Number(elements.pngScale.value),elements.title.value,elements.layout.value);elements.status.textContent='PNG download prepared locally.';}catch(error){elements.status.textContent=error instanceof Error?error.message:'PNG export failed.';}finally{updateExportAvailability();}}
function currentProjectSnapshot(){if(!route)throw new Error('Create or import a route before saving a project.');return currentProject?updateProject(currentProject,{route,composition:compositionState(),title:elements.title.value}):createProject({route,composition:compositionState(),title:elements.title.value});}
async function handleSaveProject(){try{currentProject=currentProjectSnapshot();await saveProject(currentProject);elements.status.textContent=`Project “${currentProject.title}” saved in this browser.`;}catch(error){elements.status.textContent=error instanceof Error?error.message:'The project could not be saved.';}}
async function handleOpenLatestProject(){try{const[summary]=await listProjects();if(!summary)throw new Error('No locally saved projects were found in this browser.');const project=validateProject(await loadProject(summary.id));applyRoute(project.route,`Project ${project.title}`,project.composition,project);}catch(error){elements.status.textContent=error instanceof Error?error.message:'The project could not be opened.';}}
function handleExportProject(){try{currentProject=currentProjectSnapshot();exportProjectFile(currentProject);elements.status.textContent='Portable .rssproj file prepared locally.';}catch(error){elements.status.textContent=error instanceof Error?error.message:'The project could not be exported.';}}
async function handleImportProject(file){const token=++operation;try{elements.status.textContent=`Opening ${file.name}…`;const project=await importProjectFile(file);if(token===operation)applyRoute(project.route,`Project ${project.title}`,project.composition,project);}catch(error){if(token===operation)fail(error);}}

for(const provider of PROVIDERS){const option=document.createElement('option');option.value=provider.id;option.textContent=provider.name;elements.provider.append(option);}const saved=loadProviderSettings();elements.provider.value=saved.providerId;elements.providerKey.value=saved.apiKey;elements.rememberProvider.checked=saved.remember;updateBudget();
elements.reviewMapLink.addEventListener('click',reviewMapLink);elements.expandMapLink.addEventListener('click',expandShortLink);elements.resolverEndpoint.value=localStorage.getItem(SHORT_LINK_GATEWAY_STORAGE_KEY)||'';elements.rememberResolver.checked=Boolean(elements.resolverEndpoint.value);elements.mapLink.addEventListener('keydown',(event)=>{if(event.key==='Enter'){event.preventDefault();reviewMapLink();}});elements.resolvePlaces.addEventListener('click',resolvePlaces);elements.buildRoute.addEventListener('click',buildResolvedRoute);elements.clearProvider.addEventListener('click',()=>{clearProviderSettings();elements.providerKey.value='';elements.rememberProvider.checked=false;elements.providerStatus.textContent='Saved provider credentials cleared from this browser.';});
elements.file.addEventListener('change',()=>{const[file]=elements.file.files;if(file)loadFile(file);});elements.projectFile.addEventListener('change',()=>{const[file]=elements.projectFile.files;if(file)handleImportProject(file);});elements.dropZone.addEventListener('keydown',(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();elements.file.click();}});for(const name of['dragenter','dragover'])elements.dropZone.addEventListener(name,(event)=>{event.preventDefault();elements.dropZone.classList.add('dragging');});for(const name of['dragleave','drop'])elements.dropZone.addEventListener(name,(event)=>{event.preventDefault();elements.dropZone.classList.remove('dragging');});elements.dropZone.addEventListener('drop',(event)=>{const[file]=event.dataTransfer.files;if(file?.name.toLowerCase().endsWith('.rssproj'))handleImportProject(file);else if(file)loadFile(file);});
for(const control of[elements.title,elements.backgroundMode,elements.backgroundOpacity,elements.overlayOpacity,elements.subtitle,elements.lineWidth,elements.showElevation,elements.showDuration,elements.showMarkers,elements.layout,elements.units,elements.routeColour,elements.backgroundColour,elements.textColour])control.addEventListener('input',scheduleRender);
elements.sample.addEventListener('click',async()=>{const token=++operation;try{elements.status.textContent='Loading sample route…';const response=await fetch('public/samples/sample-route.gpx',{cache:'no-store'});if(!response.ok)throw new Error('The sample route could not be loaded.');const text=await response.text();if(token===operation)applyRoute(parseGpx(text,'sample-route.gpx'),'Sample route');}catch(error){if(token===operation)fail(error);}});elements.reset.addEventListener('click',reset);elements.downloadSvg.addEventListener('click',()=>{if(currentSvg)downloadSvg(currentSvg,elements.title.value,elements.layout.value);});elements.downloadPng.addEventListener('click',handlePngExport);elements.downloadJpeg.addEventListener('click',handleJpegExport);elements.addAnnotation.addEventListener('click',()=>{const label=elements.annotationLabel.value.trim();if(!label){elements.annotationStatus.textContent='Enter a label first.';return;}annotations.push({id:`annotation-${Date.now()}`,label,positionPercent:Number(elements.annotationPosition.value)});elements.annotationLabel.value='';elements.annotationStatus.textContent=`${annotations.length} annotation${annotations.length===1?'':'s'} added.`;scheduleRender();});elements.clearAnnotations.addEventListener('click',()=>{annotations=[];elements.annotationStatus.textContent='No annotations added.';scheduleRender();});elements.saveProject.addEventListener('click',handleSaveProject);elements.openLatest.addEventListener('click',handleOpenLatestProject);elements.exportProject.addEventListener('click',handleExportProject);elements.importProject.addEventListener('click',()=>elements.projectFile.click());elements.backgroundMode.addEventListener('change',()=>{if(elements.backgroundMode.value==='map'&&backgroundAsset?.mode!=='map')backgroundAsset=null;updateBackgroundControls();if(elements.backgroundMode.value==='solid')backgroundAsset=null;scheduleRender();});elements.backgroundImage.addEventListener('change',()=>{const[file]=elements.backgroundImage.files;if(file)handlePhoto(file);});elements.mapConsent.addEventListener('click',loadMap);elements.mapZoomOut.addEventListener('click',()=>adjustMapZoom(-1));elements.mapZoomIn.addEventListener('click',()=>adjustMapZoom(1));elements.downloadGeneratedGpx.addEventListener('click',()=>{if(!route||!currentReceipt)return;currentGeneratedGpx=generateGpx(route,currentReceipt,{denseGeometry:elements.denseGpx.checked});downloadGeneratedText(currentGeneratedGpx,route.title,'gpx','application/gpx+xml');});elements.downloadGeneratedKml.addEventListener('click',()=>{if(currentGeneratedKml)downloadGeneratedText(currentGeneratedKml,route.title,'kml','application/vnd.google-earth.kml+xml');});elements.downloadReceipt.addEventListener('click',()=>{if(currentReceipt)downloadReceipt(currentReceipt,route.title);});updateBackgroundControls();
